spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root1818
  thymeleaf:
    cache: false

server:
  port: 8081

logging:
  level:
    com.hzslb.securitydemo.mapper:DEBUG
    org.springframework.security:INFO

mybatis:
  configuration:
    map-underscore-to-camel-case: true

